C2SP/C2SP

age.md
Noticed this while reading through the age specification and the draft plugin spec. I didn't see any precedent in this doc for uppercase vs. lowercase hex; went with lowercase, but happy to change if you prefer.
In any case, thank you for all your work on age and open source!
=> age: Fix byte value typo.

age.md
Previously, a 64 KiB payload could be encrypted as one or two chunks.
All known implementations do the former. Remove the complexity and
ambiguity by requiring that.
=> age: tighten STREAM last chunk

vrf-r255.md
The only [differences on top of draft-irtf-cfrg-vrf-11](https://www.ietf.org/rfcdiff?url1=draft-irtf-cfrg-vrf-11&url2=draft-irtf-cfrg-vrf-15&difftype=--html) were a change to use "secret key" instead of "private key", changes to "Section 3: VRF Security Properties" and "Section 7: Security Considerations" that are purely editorial, and test vectors for the RSA ciphersuites.
=> vrf-r255: Update references to point to draft-irtf-cfrg-vrf-15

sunlight.md
It was pointed out that it's technically possible to sequence but not commit entries, although that's not what the Sunlight implementation does.
=> sunlight: weaken null MMD language

XAES-256-GCM.md
See https://github.com/dchest/xaes.
=> XAES-256-GCM: note that AES-CBC is sufficient

tlog-cosignature.md, tlog-witness.md
Previously at https://git.glasklar.is/sigsum/project/documentation/-/blob/main/witness.md
=> tlog-witness: new spec imported from Sigsum

static-ct-api.md, tlog-tiles.md
This PR changes references to `Content-Type: application/data` to `Content-Type: application/octet-stream` in the `static-ct-api` and `tlog-tiles` specs.
`application/octet-stream` is an [IANA registered type](https://www.iana.org/assignments/media-types/application/octet-stream), but `application/data` is not.
=> Replace application/data with application/octet-stream

age-plugin.md
Designed with @FiloSottile.
This extension to `recipient-v1` enables clients to require that plugins provide a set of labels at encryption time. These labels are used to restrict which stanzas can appear together in the same file header.
We don't make any changes to `identity-v1` because decryption time restrictions are pointless: an attacker can drop stanzas or reuse the single stanza.
This can be used for
- Authentication (auth X25519, scrypt) by setting a random label.
- PQC by setting a well-known label.
- Corp approval by setting a private but potentially shared label.
=> age-plugin: Add labels extension to `recipient-v1`

XAES-256-GCM.md
The markdown link for AES-GEM was missing a link, so it currently renders the literal text `[AES-GEM]:` at the foot of the document.
I took a guess as to what the link should be, but the GitHub repository seemed like a reasonable first guess. Happy to update it if y'all think it should go elsewhere.
=> Update XAES-256-GCM.md with AES-GEM link

age-plugin.md
A plugin might be invoked with a single recipient encoding, but return multiple stanzas, e.g. to support multiple formats, to build group aliases, or to act as a proxy.
We tried and failed to figure out why this was added, but it was probably before we properly abstracted file headers stanzas from recipients.
=> age-plugin: allow multiple stanzas

static-ct-api.md
RFC6962 specifies that a `TreeHeadSignature` includes an `uint64` `tree_size`.  That means that there cannot be more than `2^64` leaves, i.e `2^56` entries bundles, i.e a maximum of 7 tile levels.
=> Cap max tile level at 6

static-ct-api.md
Following up on: https://github.com/C2SP/C2SP/issues/95
=> static-ct-api: clarify how pre_certificate maps to RFC6962

signed-note.md
Generally, it's good to surface issues when they can be detected sooner rather than later, and explicitly if possible.
For example, consider the case of rotating a key. You'll want to use the old and new keys in parallel for a while. If the new key is producing invalid signatures you might not learn about it until you decommission the old key, if clients were failing to verify the signature from the new key but silently ignoring it once they verify the signature from the old key. Instead, stricter clients will fail sooner, ideally in testing.
We live in a post-Postel's world.
Going from MAY to SHOULD is just a recommendation change, it doesn't change the interoperability requirements.
This was discussed at the last Sigsum meetup.
=> signed-note: turn invalid sig from known key from MAY to SHOULD reject

static-ct-api.md
This was implied by the statement that logs MAY select it without negotiation, but make it clearer with a client-side MUST.
=> static-ct-api: clarify clients MUST support gzip

static-ct-api.md
It's "Ct" rather than "CT" in RFC 6962.
=> static-ct-api: Correct the case of the CtExtensions type

tlog-witness.md
All of the other tlog specs have titles like "Transparency Log Foos", while tlog-witness is "The Witness Protocol". Rename to match.
(I have no horse in this race at all. I just noticed the discrepancy while I was looking at other stuff and figured I'd upload as a mini suggestion. If you all prefer "The Witness Protocol" or it would be annoying to re-title for some reason, just leave it as-is.)
=> tlog-witness: change title to match other tlog specs

tlog-tiles.md
This seems to be the only C2SP document without one. Add one so it's easier to cite. I went with "Tiled Transparency Logs" because that's how the document seems to refer to this ("A tiled transparency log is defined by ...").
The other tlog documents are named like "Transparency Log Cosignatures", which would suggest "Transparency Log Tiles", but the document is the entrypoint for the whole tlog API, so "Tiled Transparency Logs" seemed more appropriate.
=> tlog-tiles: add a title

tlog-cosignature.md
This PR puts a maintainer's touch on https://github.com/C2SP/C2SP/pull/140 by targeting continued use of cosignature/v1 rather than going up to cosignature/v2. This does not mean we did not like the suggested cosignature/v2 changes (witness name is tied to the cosignature and can be used as a signing context), but rather that we want to be sure there aren't other things we also want in a cosignature/v2. One way to view this is: while it's a painpoint to manage multiple keys for different cosigning contexts, it's also a painpoint to manage multiple different cosignature versions. So we want to avoid creating a cosignature/v2 prematurely and start by making a backwards compatible update to the text in cosignature/v1.
Blocking merge:
* Input from @davidben, @lukevalenta: are you happy with …
=> tlog-cosignature: Allow additional statements

tlog-cosignature.md
The URL has contents now, so no more need to cite a PR.
=> tlog-cosignature: cite stable tlog-mirror URL

tlog-mirror.md
Now that the underlying machinery is in, add a little bit of text to tlog-mirror, which should let us remove one of the TODO sections in Merkle Tree Certificates.
=> tlog-mirror: Add a little text to discuss how it interacts with pruning
